---
  - name: Update apt cache if needed
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade OS
    apt: upgrade=dist force=yes

  - name: Install needed packages
    apt: pkg={{item}} state=installed
    with_items:
      - logrotate
      - curl
      - git
      - update-motd
      - vim

  - name: Check if anything needs autoremoving
    shell: apt-get -y --dry-run autoremove | grep -q "0 to remove"
    register: check_autoremove
    ignore_errors: True
    changed_when: False
    always_run: True

  - name: Autoremove unused packages
    command: apt-get -y autoremove
    when: "check_autoremove.rc != 0"

  - name: Disable periodic OS update checks
    lineinfile: dest=/etc/apt/apt.conf.d/10periodic regexp="^APT::Periodic::Update-Package-Lists \"1\"" line="APT::Periodic::Update-Package-Lists \"0\";" state=present
    ignore_errors: true

  - name: Create the deploy user
    user: name={{user}} comment="deploy user" generate_ssh_key=yes ssh_key_bits=2048 state=present shell=/bin/bash

  - name: Copy ssh keys to the user's .ssh directory
    copy: src=ssh_keys.pub dest=/home/{{user}}/.ssh/authorized_keys mode=0700 owner={{user}} group={{user}}

  - name: Set {{user}} as sudoer
    lineinfile: "dest=/etc/sudoers line='{{user}} ALL=(ALL) NOPASSWD : ALL'"

  - name: Remove ubuntu's user
    user: name=ubuntu state=absent remove=yes

  - name: FW Allow everything
    ufw: state=enabled policy=allow

  - name: Set vi preferences
    copy: src=vimrc dest=/home/{{user}}/.vimrc owner={{user}} group={{user}}

